app = "salesforce-mcp-server"
primary_region = "ams"

[build]
  # utilise le Dockerfile à la racine

[env]
  SF_INSTANCE_URL = "https://crmcnas--devstab.sandbox.my.salesforce.com"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    hard_limit = 10
    soft_limit = 5