app = "mcp-salesforce-server"
primary_region = "cdg"

[[files]]
  guest_path = "/app/assets/server.key"
  secret_name = "SF_JWT_PRIVATE_KEY"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443