app = "mcp-salesforce-server"
primary_region = "cdg"

[env]
  SF_INSTANCE_URL = "https://test.salesforce.com"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443